### ISSUE TITLE
Not seeing any reports - noob alert

### ISSUE THREAD

**Issue by gsuttie** [alex-seville/blanket#244]
Ok I admit I may be missing something obvious here but I cannot see what I am doing wrong.

I have a .js file called code.js with 3 very simple methods and a test .js file for the code - in jasmine I can run the test using chutzpah not problem all works nicely. I want to get this working so I can see the coverage results when I run the specrunner for jasmine within visual studio - the test are passing but I see no code coverage results and i'm a little confused as to what goes where and could use some advice.

All files are in the Scripts folder.

So I have jasmine-blanket, blanket.min.js, jasmine-html.js and my code.js and codetest.js all inside the scripts folder.

At the top of the jasmine-blanket I have referenced blanket.min.js

When I run the specrunner page I see my tests execute and pass but no output for code coverage - missing something obvious.

Thanks for any advice 

Greg

![codecoverage](https://f.cloud.github.com/assets/373279/268213/479681ea-8f15-11e2-8863-67ff10a08273.png)

**Comment by anywhichway** [comment]
Adding a comment here because I am having the same behavior but have not been able to resolve the issue in Firefox or Edge using any of the above steps. Below is the test setup file. After loading the results are as follows:

1) Test scripts run fine
2) window.blanket is defined
3) _$blanket is not defined

GitHub is up to date for https://github.com/anywhichway/proxy-observe in case you are suspicious it is the nature of the code base causing the issue. Mocha, Chai, and Blanket are all dev dependencies and you will not see them in the repository, although they are on the dev machine.

I also tried to set-up QUnit, but the checkbox for enabling test coverage never appeared on the QUnit dashboard.

```
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" media="all" href="../node_modules/mocha/mocha.css">
</head>
<body>
<div id="mocha"></div>
<div id="messages"></div>
<div id="fixtures"></div>
<script src="../node_modules/mocha/mocha.js" type="text/javascript"></script>
<script src="../node_modules/chai/chai.js" type="text/javascript"></script>
<script src="../node_modules/blanket/src/blanket.js" data-cover-flags="debug" data-cover-adapter="mocha-blanket.js"></script>
<script>
mocha.setup('bdd');
var expect = chai.expect;
</script>
<script src="../browser/proxy-observe.js" type="text/javascript" data-cover></script>
<script src="./index.js" type="text/javascript"></script>
<script>mocha.run();</script>
</body>
</html>
```

**Comment by alex-seville** [comment]
You may want to try updating to version 1.2.2 of blanket to see if it helps.
