### ISSUE TITLE
Generator not support?

### ISSUE THREAD

**Issue by fengmk2** [alex-seville/blanket#393]
I run the coverage test on koa app, it throw:

```
$ m cov

/Users/mk2/git/koa-gzip/node_modules/blanket/node_modules/esprima/esprima.js:3872
            throw e;
                  ^
Error: Line 27: Unexpected token *
    at throwError (/Users/mk2/git/koa-gzip/node_modules/blanket/node_modules/esprima/esprima.js:1156:21)
    at throwUnexpected (/Users/mk2/git/koa-gzip/node_modules/blanket/node_modules/esprima/esprima.js:1213:9)
```

**Comment by ilkkao** [comment]
ES6 support would be nice. It's becoming more and more popular because of good support in io.js and modern browsers.

**Comment by markhuge** [comment]
+1

**Comment by ZheFeng** [comment]
+1

**Comment by mattma** [comment]
+1 same here

**Comment by mattma** [comment]
@fengmk2 Is there an alternative code coverage tool which could run generators?

**Comment by alex-seville** [comment]
The parser that Blanket uses has partial support for ES6: http://esprima.org/doc/es6.html

I suspect that Istanbul (https://github.com/gotwarlost/istanbul) is using a more recent version of Esprima then Blanket, but I don't believe it works for client side testing yet.

**Comment by mattma** [comment]
I actually run Blanket to test my server side application. It works for me when I use Node/Express.js server side javascript testing via [gulp-blanket-mocha](https://github.com/dylanb/gulp-blanket-mocha). Here is the Gulp code.

```js
gulp.task('coverage', function () {
  // Test which need to run again src folder
  // one test per line
  var src = [
    'server/test/routes/api/**/*.spec.js'
  ];
  // Source folder need to be tested on
  // one source per line
  // match what is passing from the `src` array
  var instrument = [
    'server/routes/api/'
  ];

  return gulp.src(src, {read: false})
    .pipe($.blanketMocha({
      instrument:  instrument,
      captureFile: 'coverage.html',
      reporter:    'html-cov'
    }));
});
```

Then I used the exactly same gulp code above, tried in my newer refactored version Node/Koa.js with the exactly same structure and logic. The only difference is using ES6 generators and Koa.js Coroutine. And the `gulp` coverage task actually hangs. 

I want to take the initiative on building a newer version of the `gulp-blanket` since the other one seems dead without any activity for over a year now. 

If you could help me along the way, it would be awesome.

**Comment by fengmk2** [comment]
@mattma I had switch to istanbul after this issue I added.

**Comment by fengmk2** [comment]
@mattma [gulp-istanbul](https://github.com/SBoudrias/gulp-istanbul) for you.
